//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kupanga.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteComponent
    {
        public int QuoteComponentId { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public int ComponentId { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual SubmittedQuote SubmittedQuote { get; set; }
    }
}
