//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kupanga.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmittedQuote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubmittedQuote()
        {
            this.QuoteComponents = new HashSet<QuoteComponent>();
        }
    
        public int QuoteId { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactStreetAddress { get; set; }
        public string ContactCity { get; set; }
        public string ContactState { get; set; }
        public string ContactZip { get; set; }
        public string HandledBy { get; set; }
        public int HomeId { get; set; }
        public int Status { get; set; }
        public Nullable<int> DoorId { get; set; }
        public Nullable<int> WindowId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> RoofId { get; set; }
        public string ContactPhoneNumber { get; set; }
    
        public virtual Home Home { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteComponent> QuoteComponents { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Component Component { get; set; }
        public virtual Component Component1 { get; set; }
        public virtual Component Component2 { get; set; }
        public virtual Component Component3 { get; set; }
    }
}
